#Left Prompt
format = '\[$username<>$hostname\]>\[$directory\]>$fill$all$cmd_duration$shell$line_break$character'

[username]
show_always = true
format = '[$user]($style)'
style_root = 'bold red'
style_user = 'fg:bright-cyan'

[hostname]
ssh_only = false 
format = '[$hostname]($style)'
style = 'fg:75'

[directory]
truncation_length = 5
truncate_to_repo = true
read_only = 'ï ½'
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'fg:198'

[fill]
symbol = ' '

[cmd_duration]
min_time = 2_000
format = '<\[[$duration]($style)\]'

[character]
success_symbol = '[>>](bold green) '
error_symbol = '[>>](bold red) '
vicmd_symbol = '[V](bold green)'

[shell]
zsh_indicator = 'zsh'
bash_indicator = 'bsh'
format = '<\[[$indicator]($style)\]'
style = 'bright-white'
disabled = false

[aws]
format = '<\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[c]
format = '<\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '<\[[$symbol($version)]($style)\]'

[cobol]
format = '<\[[$symbol($version)]($style)\]'

[conda]
format = '<\[[$symbol$environment]($style)\]'

[crystal]
format = '<\[[$symbol($version)]($style)\]'

[dart]
format = '<\[[$symbol($version)]($style)\]'

[deno]
format = '<\[[$symbol($version)]($style)\]'

[docker_context]
format = '<\[[$symbol$context]($style)\]'

[dotnet]
format = '<\[[$symbol($version)(ðŸŽ¯ $tfm)]($style)\]'

[elixir]
format = '<\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '<\[[$symbol($version)]($style)\]'

[erlang]
format = '<\[[$symbol($version)]($style)\]'

[gcloud]
format = '<\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '<\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '<\[[$symbol($version)]($style)\]'

[haskell]
format = '<\[[$symbol($version)]($style)\]'

[helm]
format = '<\[[$symbol($version)]($style)\]'

[hg_branch]
format = '<\[[$symbol$branch]($style)\]'

[java]
format = '<\[[$symbol($version)]($style)\]'

[julia]
format = '<\[[$symbol($version)]($style)\]'

[kotlin]
format = '<\[[$symbol($version)]($style)\]'

[kubernetes]
format = '<\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '<\[[$symbol($version)]($style)\]'

[memory_usage]
format = '<\[$symbol[$ram( | $swap)]($style)\]'

[nim]
format = '<\[[$symbol($version)]($style)\]'

[nix_shell]
format = '<\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '<\[[$symbol($version)]($style)\]'

[ocaml]
format = '<\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '<\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '<\[[$symbol$version]($style)\]'

[perl]
format = '<\[[$symbol($version)]($style)\]'

[php]
format = '<\[[$symbol($version)]($style)\]'

[pulumi]
format = '<\[[$symbol$stack]($style)\]'

[purescript]
format = '<\[[$symbol($version)]($style)\]'

[python]
format = '<\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[red]
format = '<\[[$symbol($version)]($style)\]'

[ruby]
format = '<\[[$symbol($version)]($style)\]'

[rust]
format = '<\[[$symbol($version)]($style)\]'

[scala]
format = '<\[[$symbol($version)]($style)\]'

[spack]
format = '<\[[$symbol$environment]($style)\]'

[sudo]
format = '<\[[as $symbol]\]'

[swift]
format = '<\[[$symbol($version)]($style)\]'

[terraform]
format = '<\[[$symbol$workspace]($style)\]'

# [time]
# format = '<\[[$time]($style)\]'

[vagrant]
format = '<\[[$symbol($version)]($style)\]'

[vlang]
format = '<\[[$symbol($version)]($style)\]'

[zig]
format = '<\[[$symbol($version)]($style)\]'

